resourcematchApi:
  deploymentDomain:
  image:
    name: <account>.dkr.ecr.<region>.amazonaws.com/resourcematch-api
    tag: sha
  openaiKey:
resourcematchApp:
  deploymentDomain:
  image:
    name: <account>.dkr.ecr.<region>.amazonaws.com/resourcematch-app
    tag: sha
