services:
  resourcematch-api:
    build:
      context: ./resourcematch-api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    environment:
      - OPENAI_API_KEY
    volumes:
      - ./resourcematch-api:/code
    ports:
      - 8888:80
    networks:
      - resourcematch
networks:
  resourcematch:
