apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-resourcematch-app
  labels:
    app: {{ .Chart.Name }}-resourcematch-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-resourcematch-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-resourcematch-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-resourcematch-app
          image: {{ .Values.resourcematchApp.image.name }}:{{ .Values.resourcematchApp.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NGINX_HOST
              value: {{ .Values.resourcematchApp.deploymentDomain }}
            - name: NGINX_PORT
              value: "80"
          ports:
            - containerPort: 80
