apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.resourcematchApi.deploymentDomain }}
spec:
  secretName: {{ .Values.resourcematchApi.deploymentDomain }}-tls
  commonName: {{ .Values.resourcematchApi.deploymentDomain }}
  dnsNames:
    - {{ .Values.resourcematchApi.deploymentDomain }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
