apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-tls-resourcematch-api
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Values.resourcematchApi.deploymentDomain }}-tls
  routes:
    - match: "Host(`{{ .Values.resourcematchApi.deploymentDomain }}`)"
      kind: Rule
      services:
        - name: {{ .Chart.Name }}-resourcematch-api
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-resourcematch-api
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.resourcematchApi.deploymentDomain }}`)"
      kind: Rule
      middlewares:
        - name: {{ .Chart.Name }}-redirect
      services:
        - name: {{ .Chart.Name }}-resourcematch-api
          port: 80
