apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-resourcematch-api
  labels:
    app: {{ .Chart.Name }}-resourcematch-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-resourcematch-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-resourcematch-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-resourcematch-api
          image: {{ .Values.resourcematchApi.image.name }}:{{ .Values.resourcematchApi.image.tag }}
          imagePullPolicy: Always
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: resourcematchApiOpenAiKey
          ports:
            - containerPort: 80
