version: 0.2

env:
  shell: bash
  secrets-manager:
    SLACK_WEBHOOKURL: "slack:k12stream"
    OPENAI_KEY: "openai:resourcematch20231117"

phases:
  install:
    commands:
      - curl -L https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz | tar -xvz
      - mv linux-amd64/helm ./helm
      - curl -L -o yq "https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64"
      - chmod +x ./helm ./yq
      - export PATH=$PWD:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --name $K8S_CLUSTER_NAME
      - export RESOURCEMATCH_API_IMAGE_NAME=$(cat $CODEBUILD_SRC_DIR_resourcematch_api_build_output/resourcematch-api-image-name.txt)
      - export RESOURCEMATCH_API_IMAGE_TAG=$(cat $CODEBUILD_SRC_DIR_resourcematch_api_build_output/resourcematch-api-image-tag.txt)
      - export RESOURCEMATCH_APP_IMAGE_NAME=$(cat $CODEBUILD_SRC_DIR_resourcematch_app_build_output/resourcematch-app-image-name.txt)
      - export RESOURCEMATCH_APP_IMAGE_TAG=$(cat $CODEBUILD_SRC_DIR_resourcematch_app_build_output/resourcematch-app-image-tag.txt)
      - touch ./values.yaml
      - yq e -i '.resourcematchApi.deploymentDomain="resourcematch-api.k12.openstax.org"' ./values.yaml
      - yq e -i '.resourcematchApi.openaiKey=strenv(OPENAI_KEY)' ./values.yaml
      - yq e -i '.resourcematchApi.image.name=strenv(RESOURCEMATCH_API_IMAGE_NAME)' ./values.yaml
      - yq e -i '.resourcematchApi.image.tag=strenv(RESOURCEMATCH_API_IMAGE_TAG)' ./values.yaml
      - yq e -i '.resourcematchApp.deploymentDomain="resourcematch.k12.openstax.org"' ./values.yaml
      - yq e -i '.resourcematchApp.image.name=strenv(RESOURCEMATCH_APP_IMAGE_NAME)' ./values.yaml
      - yq e -i '.resourcematchApp.image.tag=strenv(RESOURCEMATCH_APP_IMAGE_TAG)' ./values.yaml
  build:
    commands:
      - helm upgrade --install -f ./values.yaml raise-ai-spikes deploy/chart/
      - export SLACK_MESSAGE="raise-ai-spikes deployment completed successfully for commit $COMMIT_ID"
      - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"'\"$SLACK_MESSAGE\"'\"}' $SLACK_WEBHOOKURL"
